export interface StationInfo {
  lat: number
  lng: number
  lines: string[]
}

export const FRIEND_COLORS = [
  { bg: '#e8ff6b', border: '#c8df3b', text: '#0d0f14' },
  { bg: '#6bffd4', border: '#3bcfaa', text: '#0d0f14' },
  { bg: '#ff6b9d', border: '#df3b7d', text: '#fff' },
  { bg: '#a78bfa', border: '#7c5cf0', text: '#fff' },
  { bg: '#fb923c', border: '#d96020', text: '#fff' },
] as const

export const STATIONS: Record<string, StationInfo> = {
  // NORTH-SOUTH LINE (NS)
  "Jurong East":       { lat: 1.3331, lng: 103.7422, lines: ["NS","EW"] },
  "Bukit Batok":       { lat: 1.3489, lng: 103.7496, lines: ["NS"] },
  "Bukit Gombak":      { lat: 1.3587, lng: 103.7519, lines: ["NS"] },
  "Choa Chu Kang":     { lat: 1.3853, lng: 103.7448, lines: ["NS","BP"] },
  "Yew Tee":           { lat: 1.3971, lng: 103.7477, lines: ["NS"] },
  "Kranji":            { lat: 1.4253, lng: 103.7622, lines: ["NS"] },
  "Marsiling":         { lat: 1.4326, lng: 103.7742, lines: ["NS"] },
  "Woodlands":         { lat: 1.4368, lng: 103.7863, lines: ["NS","TE"] },
  "Admiralty":         { lat: 1.4408, lng: 103.8006, lines: ["NS"] },
  "Sembawang":         { lat: 1.4491, lng: 103.8199, lines: ["NS"] },
  "Canberra":          { lat: 1.4432, lng: 103.8297, lines: ["NS"] },
  "Yishun":            { lat: 1.4295, lng: 103.8353, lines: ["NS"] },
  "Khatib":            { lat: 1.4175, lng: 103.8330, lines: ["NS"] },
  "Yio Chu Kang":      { lat: 1.3817, lng: 103.8448, lines: ["NS"] },
  "Ang Mo Kio":        { lat: 1.3700, lng: 103.8495, lines: ["NS"] },
  "Bishan":            { lat: 1.3511, lng: 103.8481, lines: ["NS","CC"] },
  "Braddell":          { lat: 1.3404, lng: 103.8470, lines: ["NS"] },
  "Toa Payoh":         { lat: 1.3326, lng: 103.8474, lines: ["NS"] },
  "Novena":            { lat: 1.3203, lng: 103.8437, lines: ["NS"] },
  "Newton":            { lat: 1.3128, lng: 103.8381, lines: ["NS","DT"] },
  "Orchard":           { lat: 1.3046, lng: 103.8318, lines: ["NS","TE"] },
  "Somerset":          { lat: 1.3007, lng: 103.8389, lines: ["NS"] },
  "Dhoby Ghaut":       { lat: 1.2990, lng: 103.8456, lines: ["NS","NE","CC"] },
  "City Hall":         { lat: 1.2932, lng: 103.8520, lines: ["NS","EW"] },
  "Raffles Place":     { lat: 1.2839, lng: 103.8514, lines: ["NS","EW"] },
  "Marina Bay":        { lat: 1.2764, lng: 103.8546, lines: ["NS","CE","TE"] },
  "Marina South Pier": { lat: 1.2706, lng: 103.8635, lines: ["NS"] },

  // EAST-WEST LINE (EW)
  "Pasir Ris":         { lat: 1.3728, lng: 103.9494, lines: ["EW"] },
  "Tampines":          { lat: 1.3527, lng: 103.9452, lines: ["EW","DT"] },
  "Simei":             { lat: 1.3432, lng: 103.9530, lines: ["EW"] },
  "Tanah Merah":       { lat: 1.3273, lng: 103.9462, lines: ["EW","CG"] },
  "Bedok":             { lat: 1.3240, lng: 103.9300, lines: ["EW"] },
  "Kembangan":         { lat: 1.3212, lng: 103.9122, lines: ["EW"] },
  "Eunos":             { lat: 1.3196, lng: 103.9027, lines: ["EW"] },
  "Paya Lebar":        { lat: 1.3179, lng: 103.8920, lines: ["EW","CC"] },
  "Aljunied":          { lat: 1.3163, lng: 103.8829, lines: ["EW"] },
  "Kallang":           { lat: 1.3113, lng: 103.8713, lines: ["EW"] },
  "Lavender":          { lat: 1.3073, lng: 103.8631, lines: ["EW"] },
  "Bugis":             { lat: 1.3009, lng: 103.8565, lines: ["EW","DT"] },
  "Tanjong Pagar":     { lat: 1.2765, lng: 103.8458, lines: ["EW"] },
  "Outram Park":       { lat: 1.2801, lng: 103.8394, lines: ["EW","NE","TE"] },
  "Tiong Bahru":       { lat: 1.2863, lng: 103.8272, lines: ["EW"] },
  "Redhill":           { lat: 1.2898, lng: 103.8166, lines: ["EW"] },
  "Queenstown":        { lat: 1.2946, lng: 103.8059, lines: ["EW"] },
  "Commonwealth":      { lat: 1.3026, lng: 103.7984, lines: ["EW"] },
  "Buona Vista":       { lat: 1.3070, lng: 103.7898, lines: ["EW","CC"] },
  "Dover":             { lat: 1.3113, lng: 103.7786, lines: ["EW"] },
  "Clementi":          { lat: 1.3152, lng: 103.7651, lines: ["EW"] },
  "Chinese Garden":    { lat: 1.3424, lng: 103.7323, lines: ["EW"] },
  "Lakeside":          { lat: 1.3440, lng: 103.7211, lines: ["EW"] },
  "Boon Lay":          { lat: 1.3388, lng: 103.7063, lines: ["EW"] },
  "Pioneer":           { lat: 1.3368, lng: 103.6969, lines: ["EW"] },
  "Joo Koon":          { lat: 1.3277, lng: 103.6786, lines: ["EW"] },
  "Gul Circle":        { lat: 1.3193, lng: 103.6605, lines: ["EW"] },
  "Tuas Crescent":     { lat: 1.3212, lng: 103.6488, lines: ["EW"] },
  "Tuas West Road":    { lat: 1.3298, lng: 103.6397, lines: ["EW"] },
  "Tuas Link":         { lat: 1.3399, lng: 103.6367, lines: ["EW"] },

  // CIRCLE LINE (CC)
  "Bras Basah":        { lat: 1.2967, lng: 103.8508, lines: ["CC"] },
  "Esplanade":         { lat: 1.2937, lng: 103.8555, lines: ["CC"] },
  "Promenade":         { lat: 1.2934, lng: 103.8617, lines: ["CC","DT"] },
  "Nicoll Highway":    { lat: 1.2999, lng: 103.8636, lines: ["CC"] },
  "Stadium":           { lat: 1.3066, lng: 103.8748, lines: ["CC"] },
  "Mountbatten":       { lat: 1.3064, lng: 103.8826, lines: ["CC"] },
  "Dakota":            { lat: 1.3081, lng: 103.8884, lines: ["CC"] },
  "MacPherson":        { lat: 1.3267, lng: 103.8896, lines: ["CC","DT"] },
  "Tai Seng":          { lat: 1.3356, lng: 103.8879, lines: ["CC"] },
  "Bartley":           { lat: 1.3425, lng: 103.8798, lines: ["CC"] },
  "Serangoon":         { lat: 1.3498, lng: 103.8731, lines: ["CC","NE"] },
  "Lorong Chuan":      { lat: 1.3524, lng: 103.8641, lines: ["CC"] },
  "Marymount":         { lat: 1.3491, lng: 103.8396, lines: ["CC"] },
  "Caldecott":         { lat: 1.3373, lng: 103.8392, lines: ["CC","TE"] },
  "Botanic Gardens":   { lat: 1.3223, lng: 103.8153, lines: ["CC","DT"] },
  "Farrer Road":       { lat: 1.3175, lng: 103.8072, lines: ["CC"] },
  "Holland Village":   { lat: 1.3119, lng: 103.7966, lines: ["CC"] },
  "one-north":         { lat: 1.2993, lng: 103.7873, lines: ["CC"] },
  "Kent Ridge":        { lat: 1.2942, lng: 103.7845, lines: ["CC"] },
  "Haw Par Villa":     { lat: 1.2826, lng: 103.7823, lines: ["CC"] },
  "Pasir Panjang":     { lat: 1.2761, lng: 103.7912, lines: ["CC"] },
  "Labrador Park":     { lat: 1.2725, lng: 103.8026, lines: ["CC"] },
  "Telok Blangah":     { lat: 1.2706, lng: 103.8098, lines: ["CC"] },
  "HarbourFront":      { lat: 1.2655, lng: 103.8219, lines: ["CC","NE"] },

  // NORTH EAST LINE (NE)
  "Chinatown":         { lat: 1.2845, lng: 103.8444, lines: ["NE","DT"] },
  "Clarke Quay":       { lat: 1.2884, lng: 103.8468, lines: ["NE"] },
  "Little India":      { lat: 1.3066, lng: 103.8493, lines: ["NE","DT"] },
  "Farrer Park":       { lat: 1.3122, lng: 103.8540, lines: ["NE"] },
  "Boon Keng":         { lat: 1.3192, lng: 103.8610, lines: ["NE"] },
  "Potong Pasir":      { lat: 1.3316, lng: 103.8693, lines: ["NE"] },
  "Woodleigh":         { lat: 1.3393, lng: 103.8701, lines: ["NE"] },
  "Kovan":             { lat: 1.3600, lng: 103.8850, lines: ["NE"] },
  "Hougang":           { lat: 1.3716, lng: 103.8924, lines: ["NE"] },
  "Buangkok":          { lat: 1.3831, lng: 103.8932, lines: ["NE"] },
  "Sengkang":          { lat: 1.3915, lng: 103.8953, lines: ["NE"] },
  "Punggol":           { lat: 1.4053, lng: 103.9022, lines: ["NE"] },

  // DOWNTOWN LINE (DT)
  "Bukit Panjang":     { lat: 1.3785, lng: 103.7762, lines: ["DT"] },
  "Cashew":            { lat: 1.3692, lng: 103.7845, lines: ["DT"] },
  "Hillview":          { lat: 1.3623, lng: 103.7672, lines: ["DT"] },
  "Beauty World":      { lat: 1.3413, lng: 103.7757, lines: ["DT"] },
  "King Albert Park":  { lat: 1.3356, lng: 103.7830, lines: ["DT"] },
  "Sixth Avenue":      { lat: 1.3310, lng: 103.7979, lines: ["DT"] },
  "Tan Kah Kee":       { lat: 1.3254, lng: 103.8074, lines: ["DT"] },
  "Stevens":           { lat: 1.3198, lng: 103.8261, lines: ["DT","TE"] },
  "Rochor":            { lat: 1.3035, lng: 103.8524, lines: ["DT"] },
  "Bayfront":          { lat: 1.2822, lng: 103.8597, lines: ["DT","CE"] },
  "Downtown":          { lat: 1.2795, lng: 103.8524, lines: ["DT"] },
  "Telok Ayer":        { lat: 1.2818, lng: 103.8482, lines: ["DT"] },
  "Fort Canning":      { lat: 1.2919, lng: 103.8444, lines: ["DT"] },
  "Bencoolen":         { lat: 1.2982, lng: 103.8499, lines: ["DT"] },
  "Jalan Besar":       { lat: 1.3051, lng: 103.8566, lines: ["DT"] },
  "Bendemeer":         { lat: 1.3137, lng: 103.8627, lines: ["DT"] },
  "Geylang Bahru":     { lat: 1.3219, lng: 103.8717, lines: ["DT"] },
  "Mattar":            { lat: 1.3258, lng: 103.8827, lines: ["DT"] },
  "Ubi":               { lat: 1.3295, lng: 103.8992, lines: ["DT"] },
  "Kaki Bukit":        { lat: 1.3343, lng: 103.9082, lines: ["DT"] },
  "Bedok North":       { lat: 1.3340, lng: 103.9192, lines: ["DT"] },
  "Bedok Reservoir":   { lat: 1.3360, lng: 103.9320, lines: ["DT"] },
  "Tampines West":     { lat: 1.3456, lng: 103.9380, lines: ["DT"] },
  "Tampines East":     { lat: 1.3572, lng: 103.9527, lines: ["DT"] },
  "Upper Changi":      { lat: 1.3412, lng: 103.9612, lines: ["DT"] },
  "Expo":              { lat: 1.3354, lng: 103.9611, lines: ["DT","CG"] },

  // THOMSON-EAST COAST LINE (TE)
  "Woodlands North":     { lat: 1.4479, lng: 103.7863, lines: ["TE"] },
  "Woodlands South":     { lat: 1.4234, lng: 103.7863, lines: ["TE"] },
  "Springleaf":          { lat: 1.3991, lng: 103.8209, lines: ["TE"] },
  "Lentor":              { lat: 1.3853, lng: 103.8364, lines: ["TE"] },
  "Mayflower":           { lat: 1.3714, lng: 103.8374, lines: ["TE"] },
  "Bright Hill":         { lat: 1.3613, lng: 103.8352, lines: ["TE"] },
  "Upper Thomson":       { lat: 1.3511, lng: 103.8309, lines: ["TE"] },
  "Mount Pleasant":      { lat: 1.3268, lng: 103.8357, lines: ["TE"] },
  "Napier":              { lat: 1.3058, lng: 103.8222, lines: ["TE"] },
  "Orchard Boulevard":   { lat: 1.3026, lng: 103.8268, lines: ["TE"] },
  "Great World":         { lat: 1.2944, lng: 103.8318, lines: ["TE"] },
  "Havelock":            { lat: 1.2884, lng: 103.8357, lines: ["TE"] },
  "Maxwell":             { lat: 1.2797, lng: 103.8444, lines: ["TE"] },
  "Shenton Way":         { lat: 1.2774, lng: 103.8507, lines: ["TE"] },
  "Gardens by the Bay":  { lat: 1.2818, lng: 103.8637, lines: ["TE"] },
  "Tanjong Rhu":         { lat: 1.2948, lng: 103.8711, lines: ["TE"] },
  "Katong Park":         { lat: 1.2994, lng: 103.8843, lines: ["TE"] },
  "Tanjong Katong":      { lat: 1.3007, lng: 103.8958, lines: ["TE"] },
  "Marine Parade":       { lat: 1.3023, lng: 103.9058, lines: ["TE"] },
  "Marine Terrace":      { lat: 1.3046, lng: 103.9138, lines: ["TE"] },
  "Siglap":              { lat: 1.3106, lng: 103.9272, lines: ["TE"] },
  "Bayshore":            { lat: 1.3146, lng: 103.9410, lines: ["TE"] },
  "Bedok South":         { lat: 1.3202, lng: 103.9473, lines: ["TE"] },
  "Sungei Bedok":        { lat: 1.3278, lng: 103.9577, lines: ["TE"] },
}

export const EDGES: Record<string, string[]> = {
  // NS Line
  "Jurong East":       ["Bukit Batok","Clementi"],
  "Bukit Batok":       ["Jurong East","Bukit Gombak"],
  "Bukit Gombak":      ["Bukit Batok","Choa Chu Kang"],
  "Choa Chu Kang":     ["Bukit Gombak","Yew Tee"],
  "Yew Tee":           ["Choa Chu Kang","Kranji"],
  "Kranji":            ["Yew Tee","Marsiling"],
  "Marsiling":         ["Kranji","Woodlands"],
  "Woodlands":         ["Marsiling","Admiralty","Woodlands North","Woodlands South"],
  "Admiralty":         ["Woodlands","Sembawang"],
  "Sembawang":         ["Admiralty","Canberra"],
  "Canberra":          ["Sembawang","Yishun"],
  "Yishun":            ["Canberra","Khatib"],
  "Khatib":            ["Yishun","Yio Chu Kang"],
  "Yio Chu Kang":      ["Khatib","Ang Mo Kio"],
  "Ang Mo Kio":        ["Yio Chu Kang","Bishan"],
  "Bishan":            ["Ang Mo Kio","Braddell","Marymount","Lorong Chuan"],
  "Braddell":          ["Bishan","Toa Payoh"],
  "Toa Payoh":         ["Braddell","Novena"],
  "Novena":            ["Toa Payoh","Newton"],
  "Newton":            ["Novena","Orchard","Stevens"],
  "Orchard":           ["Newton","Somerset","Orchard Boulevard","Napier"],
  "Somerset":          ["Orchard","Dhoby Ghaut"],
  "Dhoby Ghaut":       ["Somerset","City Hall","Clarke Quay","Bras Basah","Bencoolen"],
  "City Hall":         ["Dhoby Ghaut","Raffles Place","Bugis","Esplanade"],
  "Raffles Place":     ["City Hall","Marina Bay","Tanjong Pagar"],
  "Marina Bay":        ["Raffles Place","Marina South Pier","Bayfront","Shenton Way"],
  "Marina South Pier": ["Marina Bay"],

  // EW Line
  "Pasir Ris":     ["Tampines"],
  "Tampines":      ["Pasir Ris","Simei","Tampines West","Tampines East"],
  "Simei":         ["Tampines","Tanah Merah"],
  "Tanah Merah":   ["Simei","Bedok","Expo"],
  "Bedok":         ["Tanah Merah","Kembangan"],
  "Kembangan":     ["Bedok","Eunos"],
  "Eunos":         ["Kembangan","Paya Lebar"],
  "Paya Lebar":    ["Eunos","Aljunied","Dakota","MacPherson"],
  "Aljunied":      ["Paya Lebar","Kallang"],
  "Kallang":       ["Aljunied","Lavender"],
  "Lavender":      ["Kallang","Bugis"],
  "Bugis":         ["Lavender","City Hall","Rochor","Promenade"],
  "Tanjong Pagar": ["Raffles Place","Outram Park"],
  "Outram Park":   ["Tanjong Pagar","Tiong Bahru","Chinatown","Clarke Quay","Havelock","Maxwell"],
  "Tiong Bahru":   ["Outram Park","Redhill"],
  "Redhill":       ["Tiong Bahru","Queenstown"],
  "Queenstown":    ["Redhill","Commonwealth"],
  "Commonwealth":  ["Queenstown","Buona Vista"],
  "Buona Vista":   ["Commonwealth","Dover","one-north","Holland Village"],
  "Dover":         ["Buona Vista","Clementi"],
  "Clementi":      ["Dover","Jurong East"],
  "Chinese Garden":["Lakeside","Jurong East"],
  "Lakeside":      ["Chinese Garden","Boon Lay"],
  "Boon Lay":      ["Lakeside","Pioneer"],
  "Pioneer":       ["Boon Lay","Joo Koon"],
  "Joo Koon":      ["Pioneer","Gul Circle"],
  "Gul Circle":    ["Joo Koon","Tuas Crescent"],
  "Tuas Crescent": ["Gul Circle","Tuas West Road"],
  "Tuas West Road":["Tuas Crescent","Tuas Link"],
  "Tuas Link":     ["Tuas West Road"],

  // CC Line
  "Bras Basah":     ["Dhoby Ghaut","Esplanade"],
  "Esplanade":      ["Bras Basah","City Hall","Promenade"],
  "Promenade":      ["Esplanade","Nicoll Highway","Bugis","Bayfront"],
  "Nicoll Highway": ["Promenade","Stadium"],
  "Stadium":        ["Nicoll Highway","Mountbatten"],
  "Mountbatten":    ["Stadium","Dakota"],
  "Dakota":         ["Mountbatten","Paya Lebar"],
  "MacPherson":     ["Paya Lebar","Tai Seng","Mattar","Ubi"],
  "Tai Seng":       ["MacPherson","Bartley"],
  "Bartley":        ["Tai Seng","Serangoon"],
  "Serangoon":      ["Bartley","Lorong Chuan","Woodleigh","Kovan"],
  "Lorong Chuan":   ["Serangoon","Bishan"],
  "Marymount":      ["Bishan","Caldecott"],
  "Caldecott":      ["Marymount","Botanic Gardens","Upper Thomson"],
  "Botanic Gardens":["Caldecott","Farrer Road","Tan Kah Kee"],
  "Farrer Road":    ["Botanic Gardens","Holland Village"],
  "Holland Village":["Farrer Road","Buona Vista"],
  "one-north":      ["Buona Vista","Kent Ridge"],
  "Kent Ridge":     ["one-north","Haw Par Villa"],
  "Haw Par Villa":  ["Kent Ridge","Pasir Panjang"],
  "Pasir Panjang":  ["Haw Par Villa","Labrador Park"],
  "Labrador Park":  ["Pasir Panjang","Telok Blangah"],
  "Telok Blangah":  ["Labrador Park","HarbourFront"],
  "HarbourFront":   ["Telok Blangah","Outram Park"],

  // NE Line
  "Chinatown":   ["Outram Park","Clarke Quay","Telok Ayer","Fort Canning"],
  "Clarke Quay": ["Chinatown","Dhoby Ghaut"],
  "Little India":["Dhoby Ghaut","Farrer Park","Rochor","Jalan Besar"],
  "Farrer Park": ["Little India","Boon Keng"],
  "Boon Keng":   ["Farrer Park","Potong Pasir"],
  "Potong Pasir":["Boon Keng","Woodleigh"],
  "Woodleigh":   ["Potong Pasir","Serangoon"],
  "Kovan":       ["Serangoon","Hougang"],
  "Hougang":     ["Kovan","Buangkok"],
  "Buangkok":    ["Hougang","Sengkang"],
  "Sengkang":    ["Buangkok","Punggol"],
  "Punggol":     ["Sengkang"],

  // DT Line
  "Bukit Panjang":  ["Cashew"],
  "Cashew":         ["Bukit Panjang","Hillview"],
  "Hillview":       ["Cashew","Beauty World"],
  "Beauty World":   ["Hillview","King Albert Park"],
  "King Albert Park":["Beauty World","Sixth Avenue"],
  "Sixth Avenue":   ["King Albert Park","Tan Kah Kee"],
  "Tan Kah Kee":    ["Sixth Avenue","Botanic Gardens"],
  "Stevens":        ["Botanic Gardens","Newton","Mount Pleasant"],
  "Rochor":         ["Little India","Bugis"],
  "Bayfront":       ["Promenade","Marina Bay","Downtown"],
  "Downtown":       ["Bayfront","Telok Ayer"],
  "Telok Ayer":     ["Downtown","Chinatown"],
  "Fort Canning":   ["Chinatown","Bencoolen"],
  "Bencoolen":      ["Fort Canning","Jalan Besar"],
  "Jalan Besar":    ["Bencoolen","Bendemeer","Little India"],
  "Bendemeer":      ["Jalan Besar","Geylang Bahru"],
  "Geylang Bahru":  ["Bendemeer","Mattar"],
  "Mattar":         ["Geylang Bahru","MacPherson"],
  "Ubi":            ["MacPherson","Kaki Bukit"],
  "Kaki Bukit":     ["Ubi","Bedok North"],
  "Bedok North":    ["Kaki Bukit","Bedok Reservoir"],
  "Bedok Reservoir":["Bedok North","Tampines West"],
  "Tampines West":  ["Bedok Reservoir","Tampines"],
  "Tampines East":  ["Tampines","Upper Changi"],
  "Upper Changi":   ["Tampines East","Expo"],
  "Expo":           ["Upper Changi","Tanah Merah","Sungei Bedok"],

  // TE Line
  "Woodlands North":   ["Woodlands"],
  "Woodlands South":   ["Woodlands","Springleaf"],
  "Springleaf":        ["Woodlands South","Lentor"],
  "Lentor":            ["Springleaf","Mayflower"],
  "Mayflower":         ["Lentor","Bright Hill"],
  "Bright Hill":       ["Mayflower","Upper Thomson"],
  "Upper Thomson":     ["Bright Hill","Caldecott"],
  "Mount Pleasant":    ["Stevens","Caldecott"],
  "Napier":            ["Orchard","Orchard Boulevard"],
  "Orchard Boulevard": ["Napier","Orchard","Great World"],
  "Great World":       ["Orchard Boulevard","Havelock"],
  "Havelock":          ["Great World","Outram Park"],
  "Maxwell":           ["Outram Park","Shenton Way"],
  "Shenton Way":       ["Maxwell","Marina Bay"],
  "Gardens by the Bay":["Marina Bay","Tanjong Rhu"],
  "Tanjong Rhu":       ["Gardens by the Bay","Katong Park"],
  "Katong Park":       ["Tanjong Rhu","Tanjong Katong"],
  "Tanjong Katong":    ["Katong Park","Marine Parade"],
  "Marine Parade":     ["Tanjong Katong","Marine Terrace"],
  "Marine Terrace":    ["Marine Parade","Siglap"],
  "Siglap":            ["Marine Terrace","Bayshore"],
  "Bayshore":          ["Siglap","Bedok South"],
  "Bedok South":       ["Bayshore","Sungei Bedok"],
  "Sungei Bedok":      ["Bedok South","Expo"],
}

export const ALL_STATION_NAMES = Object.keys(STATIONS).sort()
